CREATE TABLE sample(
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL
)

SELECT * FROM sample

CREATE TABLE users (
  id VARCHAR(100) PRIMARY KEY,
  password VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)

ALTER TABLE users RENAME COLUMN name TO first_name;

ALTER TABLE users
  ADD COLUMN middle_name VARCHAR(100) NULL

ALTER TABLE users
  ADD COLUMN last_name VARCHAR(100) NULL

CREATE TABLE user_logs(
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  action VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)

SELECT * FROM user_logs

CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  deleted_at TIMESTAMP NULL
)